### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by benpaddlejones** [ajahiri/Student-Voice#1]
Cordove & Phone gap will want standard file structures and file locations, all files and folders must be lowercase with no spaces or special characters.

Only index.html at root
All libraries in a lib folder
All scripts in a scripts folder
All images in images folder
All CSS in a css folder

**Comment by ajahiri** [comment]
should i link the jscript and jquery in a file or keep it in index.html?

**Comment by benpaddlejones** [comment]
For simplicity and easy debugging put jquerymin.js in lib folder & link to it. Then have scripts for each of the core functions hosted in scripts folder then only call them from the index.html.

**Comment by ajahiri** [comment]
Where do you think the fonts should go?

**Comment by benpaddlejones** [comment]
With css or have a fonts folder

**Comment by ajahiri** [comment]
Alright, that's done.
