### ISSUE TITLE
You need an email that will link to the future developers accounts?

### ISSUE THREAD

**Issue by benpaddlejones** [ajahiri/Student-Voice#3]
The app manifest needs to include a developers email and website (I'll use the Github wiki as the website in the interim).

The email address will also be used to setup Android/Windows/Apple developers accounts. 

Please list the Pro & Cons in using one of your existing personal email address versus setting up a specific account for the team below.

**Comment by ajahiri** [comment]
One for a team is much better.
Pros:
- More professional
- Less cluttered than our personal emails

Cons:
- None

**Comment by benpaddlejones** [comment]
Fixed with halfbeardstudios@gmail dot com
