### ISSUE TITLE
Ripple-effect

### ISSUE THREAD

**Issue by ajahiri** [ajahiri/Student-Voice#4]
Ali, I tried to get the code for the effect and I found that it links to 3 other documents of code that have different licenses and was about >400 lines of JS. For such a simple effect, there is no need to have so much code and limit ourselves to their license.

**Comment by gypodra** [comment]
The other 2 are just the Roboto font and the icons. Don't worry about them.

**Comment by ajahiri** [comment]
Did you not read what I just said, here. Take a look at this, is this just a font or icon? 
https://www.polymer-project.org/0.5/components/polymer/polymer.js

**Comment by ajahiri** [comment]
This and a few other files are licensed. I don't see the need to go to such trouble for such a simple effect, I'm sure there is something else we can find.

**Comment by gypodra** [comment]
I'm pretty sure it's open source. It's from the Polymer Project.

**Comment by gypodra** [comment]
no it's not, my bad.

**Comment by gypodra** [comment]
Ok then, remove it so I can pull again.

**Comment by ajahiri** [comment]
Yep, I pushed it.

**Comment by ajahiri** [comment]
Btw, there's no need for you to wait for me to push it, if you work on it then push it will apply both our changes to the repo but you have to make sure that you always pull.
