### ISSUE TITLE
Research the brand "Student Voice"

### ISSUE THREAD

**Issue by benpaddlejones** [ajahiri/Student-Voice#5]
Does it already exist an any of the app stores or online?

Wikipedia brings some nice language to use in the app: https://en.wikipedia.org/wiki/Student_voice

**Comment by gypodra** [comment]
On the Apple App Store, there is a developer team that are named Student Voice. But none of their products have Student Voice in their titles.

**Comment by ajahiri** [comment]
There are also no applications named StudentVoice on the play store.
