### ISSUE TITLE
Add 	<script src="phonegap.js"></script> to index.html

### ISSUE THREAD

**Issue by benpaddlejones** [ajahiri/Student-Voice#6]
Please add "<script src="phonegap.js"></script>" in the header for improved PhoneGap support. There is no need to include phonegap.js in the lib Build PhoneGap does this on the fly.

**Comment by ajahiri** [comment]
Would you want me to link "lib/phonegap.js" not just "phonegap.js"?

**Comment by benpaddlejones** [comment]
No add as written above, as per PhokeGaps documentation, the file is inserted at the root

**Comment by ajahiri** [comment]
Done.
