### ISSUE TITLE
Lag in app

### ISSUE THREAD

**Issue by ajahiri** [ajahiri/Student-Voice#9]
Hey Sir, I noticed that there is lag with almost every animation in the app. What do we do about this?

**Comment by benpaddlejones** [comment]
I'll need to investigate, could be too much html5 which means we'll need to integrate crossroads. Just ignore for the moment and focus of getting core functionality.

**Comment by ajahiri** [comment]
Sure.

**Comment by benpaddlejones** [comment]
From what I'he read jquery is too bulky for mobile because of all the cross browser work arrounds try http://zeptojs.com/ should require no change to code.

**Comment by benpaddlejones** [comment]
Watch this too: https://youtu.be/3rF-xefoy5U fastclick look like a great include for performance

**Comment by ajahiri** [comment]
I tried to use other Jquery alternatives but I was using Jquery UI as well for the animations so I've added a small file that says it will "fix" the lag issues and it worked. But, the app doesn't feel native and it still feels really slow and clunky. I'll finish watching the video linked but it said something about using AngularJS for mobile development and I found a Codecademy course on it so I'll be doing that and trying to ditch Jquery altogether. It also mentioned this: https://crosswalk-project.org/

**Comment by gypodra** [comment]
I've heard about AngularJS before and it has been recommended a lot on
stackoverflow.
-Ali Hamieh

**Comment by benpaddlejones** [comment]
I'll make a test build during the week using crosswalk and Cordova. Hopefully this will fix. Stay focused on core functionality then deliver perforrmance. A sluggish app that does its job is infinetly better than a high perming app that does nothing. Ali, have you atleast got some sample code using a simple test to find a string within an array?

**Comment by gypodra** [comment]
I have had no luck with that, Sir. Nothing seems to be working.
-Ali Hamieh

**Comment by gypodra** [comment]
I actually may have found something. I'll get to testing when I'm on my
laptop :)
-Ali Hamieh

**Comment by benpaddlejones** [comment]
Upload some samples and things you've tried and raise a issue tagged "help"

**Comment by benpaddlejones** [comment]
Ali you are the 3rd dog: https://youtu.be/5iTTNRE-njM

**Comment by gypodra** [comment]
LOL, pretty much!
-Ali Hamieh

**Comment by benpaddlejones** [comment]
Arian I've made some changes to config.xml can you test if this has improved performance. Let me know either way then I have added zepto and fastclick to the lib folder try (1 at a time) adding fastclick to your index and test. Then replace zepto.ja with jquery and test. Let me know outcome of each.

**Comment by ajahiri** [comment]
Here are my conclusions for the performance:
jQuery+jQueryUI+fastclick -
Performance is exactly the same.

ZeptoJS+jQueryUI+Fastclick -
App is broken. We can't replace jQuery with Zepto because we are using jQueryUI, which is 100% dependent on jQuery. After some research yesterday I found out that jQuery UI doesn't used CSS transitions because it's shit like that this is why I tried that fix that would sopposedly make jQuery animations use CSS transitions. It worked (kinda) but its not that great. I wanted to spend today to learn Angular and apply all the points that were discussed in the video that you shared and see what we get. If we keep building on top of jQuery and jQueryUI, its going to get worse. By switching now, the functionality of the app will remain the same, we're just switching to a different library that will handle animations and JS better than jQuery.

**Comment by benpaddlejones** [comment]
Test with crosswalk plugin here: https://www.dropbox.com/s/i8gj3qmtb4p0qjy/android-armv7-debug.apk?dl=0

**Comment by ajahiri** [comment]
I installed the app, it's the same in terms of performance, the button effects still lag and the when selecting a text box, the moving text still lags. Also, when the keyboard comes us, the page twitches and glitches for a second.

**Comment by benpaddlejones** [comment]
Crosswalk is not the solution you've been looking for

**Comment by ajahiri** [comment]
I don't think Crosswalk would make a difference on my device since I'm running the latest version of Android and Webview, Crosswalk will be good for us with people that are using older devices that don't have the latest webview etc.

**Comment by benpaddlejones** [comment]
This has confirmed this issue is excessive JavaScript library. Something to try might be to reduce the bloat buy diving into jquery and deleting the unnecessary parts giving us a bespoke library?

**Comment by benpaddlejones** [comment]
Zepto and https://github.com/StanAngeloff/zoey/blob/develop/README.md could be the solution. Did some reading and issue might be jquery UI as it supports all the back to ie6 so is very bulky.

**Comment by benpaddlejones** [comment]
Is is closed with commits of condensed jquery ui? Or still not happy it feels native?

**Comment by ajahiri** [comment]
jQuery is fine, with the added fix file. The transitions are smooth so we'll stick to jQuery.
